exclude_paths:
  - .terraform/
  - modules/

warn_list:
  - experimental # enable experimental rules as warnings

skip_list:
  - yaml # allow simple YAML formatting differences in demo

parseable: false
quiet: false
# Basic config for demo; tighten in production
