# ===================================================================
# ANSIBLE - Configuration Management
# Purpose: Configure software on the VM (install Nginx)
# ===================================================================
---
- name: Configure web server
  hosts: webservers
  become: yes

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy podcaster web app
      ansible.builtin.copy:
        src: /tmp/podcaster-dist/
        dest: /var/www/html/
        mode: preserve
        remote_src: no
      become: yes

    - name: Verify Nginx is running
      ansible.builtin.systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Display Nginx status
      ansible.builtin.debug:
        msg: "Nginx is {{ nginx_status.status.ActiveState }}"
